Update infra.yml

diff --git a/.github/workflows/infra.yml b/.github/workflows/infra.yml
--- a/.github/workflows/infra.yml
+++ b/.github/workflows/infra.yml
@@ -36,70 +36,64 @@ jobs:
         sudo chmod +x /bin/terragrunt
         terragrunt -v
 
+      
+    - name: Terragrunt Init
+      working-directory: ./infra/environments
+      run: terragrunt init --terragrunt-non-interactive -lock=false
+
+    - name: Terragrunt Plan
+      working-directory: ./infra/environments
+      run: terragrunt plan --terragrunt-non-interactive -lock=false
+
+    - name: Terragrunt Apply
+      working-directory: ./infra/environments
+      run: terragrunt apply --auto-approve --terragrunt-non-interactive -lock=false 
+
+    - name: Terragrunt Apply
+      working-directory: ./infra/environments
+      id: apply
+      run: terragrunt apply --auto-approve --terragrunt-non-interactive -lock=false || echo "Apply failed"
 
     - name: Terragrunt Destroy
+      if: steps.apply.outcome == 'failure'
       working-directory: ./infra/environments
       run: terragrunt destroy --auto-approve --terragrunt-non-interactive -lock=false      
-
-        
-
-  #   - name: Terragrunt Init
-  #     working-directory: ./infra/environments
-  #     run: terragrunt init --terragrunt-non-interactive -lock=false
-
-  #   - name: Terragrunt Plan
-  #     working-directory: ./infra/environments
-  #     run: terragrunt plan --terragrunt-non-interactive -lock=false
-
-  #   - name: Terragrunt Apply
-  #     working-directory: ./infra/environments
-  #     run: terragrunt apply --auto-approve --terragrunt-non-interactive -lock=false 
-
-  #   - name: Terragrunt Apply
-  #     working-directory: ./infra/environments
-  #     id: apply
-  #     run: terragrunt apply --auto-approve --terragrunt-non-interactive -lock=false || echo "Apply failed"
-
-  #   - name: Terragrunt Destroy
-  #     if: steps.apply.outcome == 'failure'
-  #     working-directory: ./infra/environments
-  #     run: terragrunt destroy --auto-approve --terragrunt-non-interactive -lock=false      
     
-  #   - name: Terragrunt refresh
-  #     working-directory: ./infra/environments
-  #     run: terragrunt refresh -lock=false && terragrunt output
+    - name: Terragrunt refresh
+      working-directory: ./infra/environments
+      run: terragrunt refresh -lock=false && terragrunt output
 
-  #   - name: Terragrunt output
-  #     working-directory: ./infra/environments
-  #     run: |
-  #       TERRAGRUNT_OUTPUT=$(terragrunt output)
-  #       echo "TERRAGRUNT_OUTPUT=$TERRAGRUNT_OUTPUT" >> $GITHUB_ENV
-  #       echo "Terragrunt output variable set to: $TERRAGRUNT_OUTPUT"   
+    - name: Terragrunt output
+      working-directory: ./infra/environments
+      run: |
+        TERRAGRUNT_OUTPUT=$(terragrunt output)
+        echo "TERRAGRUNT_OUTPUT=$TERRAGRUNT_OUTPUT" >> $GITHUB_ENV
+        echo "Terragrunt output variable set to: $TERRAGRUNT_OUTPUT"   
 
 
 
-  # App-Deploy:
-  #   runs-on: ubuntu-latest
-  #   needs: Infra-Deploy
+  App-Deploy:
+    runs-on: ubuntu-latest
+    needs: Infra-Deploy
     
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v4
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
     
-  #   - name: Set up Python
-  #     uses: actions/setup-python@v2
-  #     with:
-  #       python-version: '3.9'
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.9'
       
-  #   - name: Install dependencies
-  #     working-directory: app  
-  #     run: |
-  #       pip install -r requirements.txt
-  #       pip list  # Print installed packages for debugging purposes
+    - name: Install dependencies
+      working-directory: app  
+      run: |
+        pip install -r requirements.txt
+        pip list  # Print installed packages for debugging purposes
 
-  #   - name: Install dependencies
-  #     working-directory: app  
-  #     run: python3 app.py
+    - name: Install dependencies
+      working-directory: app  
+      run: python3 app.py
 
 
 
